image: "registry.gitlab.com/congma/libsncompress/with-realdata:latest"

before_script:
  - |
    apt-get update -qq && apt-get install -y -qq \
                                          python python3 \
                                          python-pip python3-pip \
                                          python-numpy python3-numpy \
                                          python-scipy python3-scipy \
                                          python-astropy python3-astropy \
                                          python-pytest python3-pytest \
                                          tox

stages:
  - smoketest
  - test_with_data

job_smoketest:
  stage: smoketest
  script:
    - tox -c smoketest-tox.ini
  tags:
    - shared

job_test_with_data:
  stage: test_with_data
  script:
    - tox -c test_with_data-tox.ini
  tags:
    - shared
