image: "registry.gitlab.com/congma/libsncompress/with-realdata:latest"

variables:
  RESTORE_CACHE_ATTEMPTS: 3
  LSNZ_GITLAB_CI_TESTDATA_BASE: "/realdata/testdata"

before_script:
  - |
    apt-get update -qq -y && apt-get install -y -qq \
                                          python python3 \
                                          pandoc \
                                          python-pypandoc python3-pypandoc \
                                          python-setuptools \
                                          python3-setuptools \
                                          python-pip python3-pip \
                                          python-numpy python3-numpy \
                                          python-scipy python3-scipy \
                                          python-astropy python3-astropy \
                                          python-pytest python3-pytest \
                                          python-coverage python3-coverage \
                                          tox
  - pip install --upgrade --no-cache-dir pip
  - pip install --upgrade --no-cache-dir tox

stages:
  - test
  - deploy

job_test:
  stage: test
  script:
    - tox
  coverage: '/^TOTAL\b.+\s+([+-]?(?:\d*\.)?\d+%)\s*$/'
  cache:
    key: "$CI_JOB_STAGE"
    paths:
      - .tox/dist
      - .tox/py2/lib/python2.7/site-packages
      - .tox/py3/lib/python3.6/site-packages
  tags:
    - shared

.job_pypi_template: &pypi_boiler
  stage: deploy
  before_script:
    - apt-get update -qq -y && apt-get install -y -qq twine pandoc python3-pip
    - pip install --upgrade --no-cache-dir pip
    - pip install --upgrade --no-cache-dir twine
    - pip install --upgrade --no-cache-dir pypandoc
  tags:
    - shared

job_testpypi:
  <<: *pypi_boiler
  environment:
    name: testpypi
    url: https://test.pypi.org/
  only:
    - '/^v(\d+!)?\d+(\.\d+)*((a|b|rc)\d+|\.post\d+|\.dev\d+)?$/'
  variables:
    TWINE_REPOSITORY: testpypi
    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    TWINE_USERNAME: congma
  script:
    - python setup.py sdist
    - twine upload -p $GLCD_TESTPYPI_PW dist/libsncompress-*.tar.gz

job_pypi:
  <<: *pypi_boiler
  when: manual
  environment:
    name: production
    url: https://pypi.org/
  only:
    - '/^v(\d+!)?\d+(\.\d+)*$/'
  variables:
    TWINE_REPOSITORY: pypi
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    TWINE_USERNAME: congma
  script:
    - python setup.py sdist
    - twine upload -p $GLCD_PYPI_PW dist/libsncompress-*.tar.gz
