image: "registry.gitlab.com/congma/libsncompress/with-realdata:latest"

variables:
  LSNZ_GITLAB_CI_TESTDATA_BASE: "/realdata/testdata"

before_script:
  - |
    apt-get update -qq -y && apt-get install -y -qq \
                                          python python3 \
                                          pandoc \
                                          python-pypandoc python3-pypandoc \
                                          python-setuptools \
                                          python3-setuptools \
                                          python-pip python3-pip \
                                          python-numpy python3-numpy \
                                          python-scipy python3-scipy \
                                          python-astropy python3-astropy \
                                          python-pytest python3-pytest \
                                          python-coverage python3-coverage \
                                          tox
  - pip install --upgrade --no-cache-dir tox

stages:
  - test

job_test:
  stage: test
  script:
    - tox
  cache:
    key: "$CI_JOB_STAGE"
    paths:
      - .tox/dist
      - .tox/py2/lib/python2.7/site-packages
      - .tox/py3/lib/python3.6/site-packages
  tags:
    - shared
