image: "registry.gitlab.com/congma/libsncompress/with-realdata:latest"

variables:
  RESTORE_CACHE_ATTEMPTS: 3
  LSNZ_GITLAB_CI_TESTDATA_BASE: "/realdata/testdata"

before_script:
  - |
    apt-get update -qq -y && apt-get install -y -qq \
                                          python python3 \
                                          pandoc \
                                          python-pypandoc python3-pypandoc \
                                          python-setuptools \
                                          python3-setuptools \
                                          python-pip python3-pip \
                                          python-numpy python3-numpy \
                                          python-scipy python3-scipy \
                                          python-astropy python3-astropy \
                                          python-pytest python3-pytest \
                                          python-coverage python3-coverage \
                                          tox
  - pip install --upgrade --no-cache-dir pip
  - pip install --upgrade --no-cache-dir tox

stages:
  - test
  - covreport
  - deploy

job_test_py2:
  stage: test
  script:
    - tox -e py2
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .tox/py2/lib/python2.7/site-packages
  artifacts:
    expire_in: "1h30min"
    name: "arti-coverdata-$CI_JOB_STAGE-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - .coverage*
  tags:
    - shared

job_test_py3:
  stage: test
  script:
    - tox -e py3
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .tox/py3/lib/python3.6/site-packages
  artifacts:
    expire_in: "1h30min"
    name: "arti-coverdata-$CI_JOB_STAGE-$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - .coverage*
  tags:
    - shared

job_cover:
  stage: covreport
  image: ubuntu:artful
  before_script:
    - apt-get update -qq -y && apt-get install -y -qq python-coverage python-pip
    - pip install --upgrade --no-cache-dir pip
    - pip install --upgrade --no-cache-dir coverage
  variables:
    GIT_STRATEGY: none
  dependencies:
    - job_test_py2
    - job_test_py3
  script:
    - coverage combine
    - coverage report -i
  coverage: '/^TOTAL\b.+\s+([+-]?(?:\d*\.)?\d+%)\s*$/'
  tags:
    - shared

.job_pypi_template: &pypi_boiler
  stage: deploy
  before_script:
    - apt-get update -qq -y && apt-get install -y -qq twine pandoc python3-pip
    - pip install --upgrade --no-cache-dir pip
    - pip install --upgrade --no-cache-dir twine
    - pip install --upgrade --no-cache-dir pypandoc
  tags:
    - shared

job_testpypi:
  <<: *pypi_boiler
  environment:
    name: testpypi
    url: https://test.pypi.org/project/libsncompress/
  only:
    - '/^v(\d+!)?\d+(\.\d+)*((a|b|rc)\d+|\.post\d+|\.dev\d+)?$/'
  variables:
    TWINE_REPOSITORY: testpypi
    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
    TWINE_USERNAME: congma
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -p $GLCD_TESTPYPI_PW dist/libsncompress-*

job_pypi:
  <<: *pypi_boiler
  when: manual
  environment:
    name: production
    url: https://pypi.org/project/libsncompress/
  only:
    - '/^v(\d+!)?\d+(\.\d+)*(\.post\d+)?$/'
  variables:
    TWINE_REPOSITORY: pypi
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
    TWINE_USERNAME: congma
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -p $GLCD_PYPI_PW dist/libsncompress-*
