image: "registry.gitlab.com/congma/libsncompress/with-realdata:latest"

before_script:
  - |
    apt-get update -qq && apt-get install -y -qq \
                                          python python3 \
                                          python-pip python3-pip \
                                          python-numpy python3-numpy \
                                          python-scipy python3-scipy \
                                          python-astropy python3-astropy \
                                          python-pytest python3-pytest \
                                          tox

stages:
  - smoketests

job_smoketests:
  stage: smoketests
  script:
    - tox -c gitlab.com-ci-smoketests-tox.ini
  tags:
    - shared
